### ISSUE TITLE
Search results page: "English" listed twice under "Language being learned" search facet

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#76] opened 2018-03-08 16:29 UTC
The term "English" is listed twice under the "Language being learned" search facet. Each term should appear only once, and the number of the right-hand side indicate how many summaries are tagged with this term.

![image](https://user-images.githubusercontent.com/36402489/37162721-e70555aa-22ed-11e8-9be0-1c6d6ce80e5d.png)

**Comment by yf508** [comment] 2018-03-09 10:09
This strange behavior is caused by the frequent change to the data dictionary items. When we have a consistent data dictionary list on live, this problem will disappear. Also, #79 requires another update of language list, so the underlying index for all languages will be changed again.

**Comment by yf508** [comment] 2018-03-09 10:15
@RKasprowicz @SophieThompson  We need to get a stable version of data dictionaries asap, otherwise, further changes to DD will cause lots of similar problems, e.g. #76 #75 #68 #74

**Comment by RKasprowicz** [comment] 2018-03-09 13:37
@yf508 The DD for all categories in the Excel sheet are stable (I realise we made changes to Participant Type and Age of Learners, but these are now fixed). 

For #79 - If it is safest and easiest to stick with the current list of languages and not make any changes to the DD for First language of learners and Language being learned, that is fine for now. Would it be best to leave this change for the later work (for May)?

**Comment by yf508** [comment] 2018-03-13 09:39
@RKasprowicz yes, we should stick with current list of languages and focus on other issues/bugs. This bug should disappear after cleaning the data on demo/live.

**Comment by paluchas** [comment] 2018-03-13 14:59
This is correct now in demo site. I'll close this issue.

**Closed by paluchas** 2018-03-13 14:59 UTC
Labels: Priority - high, bug

**Comment by RKasprowicz** [comment] 2018-03-13 15:14
@paluchas I agree. This issue has been fixed.
